# site name
prefixName: Loe-Koyori's
siteName:  " site"
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.png
url: https://blogdemo.playmarxcards.online/
description: "\"The passion of destruction is also the passion of creation.\"" # Sin Banderas Ni Fronteras 没有国旗，没有边界
descriptionmobile: Sin Banderas Ni Fronteras 没有国旗 没有边界
cdn: https://cdn.jsdelivr.net/gh/LoeKoyori/cdn@2.2
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎来小代理家做客，要常来哦~
lazyloadImg: https://cdn.jsdelivr.net/gh/LoeKoyori/cdn@2.0/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    推介: {path: /categories/推介/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    评论: {path: /categories/评论/, fa: fa-commenting-o },
    杂谈: {path: /categories/杂谈/, fa: fa-book }
  } }
  栏目: { path: /archives, fa: fa fa-tags, submenus: { 
    笑林广记: {path: /tags/笑林广记/, fa: fa fa-star }, 
    聊斋志异: {path: /tags/聊斋志异/, fa: fa fa-star }, 
    时事评论: {path: /tags/时事评论/, fa: fa-commenting-o },
    理论探讨: {path: /tags/理论探讨/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    # 书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /photo.html, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
  } }
  APP: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t5uajgfj31hc0u01a2.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t631397j31hc0u0tns.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t68qfa2j31hc0u0n64.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t6fzb05j32mb1lqb2e.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t6uh3dnj31hc0wukjn.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t76jbqfj31z4140npf.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t7c5kt6j31hc0u04qq.jpg
  - http://tva2.sinaimg.cn/large/007gk3UJgy1gq8t7hjcy2j31hc0u0x6p.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /1926/08/17/Hello%20World/, title: Hello World, desc: 建站宣言, img: /img/startdash/helloworld.jpg}
  - {url: /about/, title: 关于我, desc: 与我对话, img: /img/startdash/bilibili.jpg}
  - {url: /client/, title: 本站Android客户端下载, desc: 但是在pc浏览本站体验更佳哦~, img: /img/cover/8.webp}



# your site build time or founded date
siteBuildingTime: 08/17/1926

#social  url, img PC端配置
social:
  github: {url: https://blogdemo.playmarxcards.online/github.html, img: /img/social/github.png}
  sina: {url: https://blogdemo.playmarxcards.online/sina.html, img: /img/social/sina.png}
  wangyiyun: {url: https://blogdemo.playmarxcards.online/wangyiyun.html, img: /img/social/wangyiyun.png}
  zhihu: {url: https://blogdemo.playmarxcards.online/zhihu.html, img: /img/social/zhihu.png}
  email: {url: https://blogdemo.playmarxcards.online/email.html, img: /img/social/email.svg}
  

#social  url, img 移动端配置
msocial:
  github: {url: https://blogdemo.playmarxcards.online/github.html, fa: fa-github, color: 333}
  weibo: {url: https://blogdemo.playmarxcards.online/weibo.html, fa: fa-weibo, color: dd4b39}
  

donate:
  paypal: ../paypal.html
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.png
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/LoeKoyori/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/LoeKoyori/video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: yezhong_o.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  mini: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.1
  mutex: true

# Valine
valine: true
v_appId: IexWd2YhBVDoxjLOtrYBgCR5-gzGzoHsz
v_appKey: z22UPGIim7pqqmGdaU7xgfbn

